### ISSUE TITLE
Disallow invalid expressions

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#17]
For the sake of simplicity, constructs like `let a = 0` are also expressions that evaluate to `()`.

As a consequence currently the following is also accepted:

![image](https://user-images.githubusercontent.com/25967296/136087255-cc6f20e8-db0d-446d-bedd-4c40f6109706.png)

It is roughly equivalent to `(this) . (const a = 2)`, It's not clear whether to leave it as is, or specify stricter rules.

**Comment by tamasfe** [comment]
I've realized that the right side of `.` should be a lot stricter and should allow identifiers only. How to restrict this properly is not immediately trivial to me as the `.` is just an operator in an expression tree where both sides can be any expression.

**Comment by schungx** [comment]
Yes, the RHS of `.` should always be an identifier.

In the parser, `.` and `[` are split off from operators.  They are actually handled as part of the parsing of a primary term, which loosely can be defined as:

    [unary operators]  identifier  ( '.' identifier |  '[' expression ']' )*

Thus, `[` and `.` are not parsed as operators, allowing you to catch invalid syntax early.
