### ISSUE TITLE
Multiple exports

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#29]
We currently support one export item per export statement, but the Rhai book has examples for comma separated exports.

**Comment by tamasfe** [comment]
I remember reading about a syntax that allowed `export foo as bar, uwu as owo;`. I can't seem to find it in the book now  though, @schungx can you help me out with this?

**Comment by schungx** [comment]
Yes, it has been removed in favor of only one export per statement to make it parallel the `import` statement.

It used to be allowed, but no more -- I think for some other reasons as well.
