### ISSUE TITLE
Support ranges

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#34]
Rhai [1.4.0](https://github.com/rhaiscript/rhai/releases/tag/v1.4.0) added range operators, these need to be added to both the parser and the HIR.

**Comment by schungx** [comment]
The HIR maybe not need a big change, since ranges is purely syntactic sugar.  They compile down to `Range` and `RangeInclusive` types.

**Comment by tamasfe** [comment]
The parser should be able to parse them now. I don't think the HIR needs any specific changes, we can just define operator types that return `Range` and `RangeInclusive` respectively whenever a type system is implemented.
