### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#45]
These are some of the issues I found running the LSP on Windows:

1. `src/ast/rhai.ungram` must have <kbd>LF</kbd> line ending.  Windows <kbd>CR</kbd>+<kbd>LF</kbd> line ending is not supported by Rowan.  Git for Windows automatically converts all line endings to Windows-style when cloning.

2. All Windows <kbd>CR</kbd>+<kbd>LF</kbd> line endings in Rhai scripts throw an `invalid input` error.

3. `print` seems to be unresolved, and it gives a hint saying maybe it should be `print`.

4. It no longer works once you start editing the code.  Before edit, popup's work fine.  After editing anything, no longer.

**Comment by schungx** [comment]
In Windows, expressions within strings interpolation does not seem to be processed.

For example:

```rust
const HELLO = 42;

let x = HELLO;    // <- press F12 on HELLO to jump to definition

let s = `Hello = ${HELLO}`;   // <- press F12 on HELLO does nothing
```

**Comment by tamasfe** [comment]
Yeah interpolated code is not yet processed, I opened an issue for it (#46).

**Comment by schungx** [comment]
![image](https://user-images.githubusercontent.com/661318/176701778-944d15bd-c2dd-4362-8557-196f343491c0.png)

`in` statements not working.

![image](https://user-images.githubusercontent.com/661318/176701824-e57bb9bc-1183-4a88-b857-f313d1df06e9.png)

Also `throw` statements.

**Comment by schungx** [comment]
Strange behavior in VScode:

1. Open `examples/main.rhai` (probably `external.d.rhai` not yet indexed)

![image](https://user-images.githubusercontent.com/661318/176865915-d31dda42-0d2c-4e6b-b8ca-918d0da7f13a.png)

2. Click on `examples/external.d.rhai` (probably indexing it)

3. Open `examples/main.rhai` again

![image](https://user-images.githubusercontent.com/661318/176866094-2806fe47-9e7f-4679-a6fe-209f38207345.png)

**Comment by schungx** [comment]
BTW, I see that you need a definition file just to put comments in modules.

Should I, say, add the `//!` doc-comments style to Rhai scripts?  They should, like Rust, go to the top of the script, and be taken as that script file's documentation.

So, `bar.rhai` can actually be simplified to:

```rust
//! Definition for "bar.rhai".
//!
//! Omitting the module path is the same as `module "./bar.rhai"`.

/// Some constant.
export const X = 10;

/// This function is private.
private fn cant_touch_this() {

}

/// This function is exported.
fn hello() {
    print("hello");
}
```

**Comment by tamasfe** [comment]
> (probably external.d.rhai not yet indexed)

That's weird, we should traverse the entire workspace after initialization and load all the files.

> Should I, say, add the //! doc-comments style to Rhai scripts? 

I'm not sure if they're worth the hassle, but yes, it'd make sense imo.

**Comment by schungx** [comment]
> I'm not sure if they're worth the hassle, but yes, it'd make sense imo.

Adding a definition file is good in the sense that we can add all sorts of nice things to it later on.

However, if scripts always need another file just to attach module docs, that will be a chore...

**Comment by schungx** [comment]
> That's weird, we should traverse the entire workspace after initialization and load all the files.

`bar.rhai` has an error (`print` again), so I'm not sure if that is tripping up all later files?

**Comment by tamasfe** [comment]
> `bar.rhai` has an error (`print` again), so I'm not sure if that is tripping up all later files?

There are still issues with adding/removing sources to the HIR (#52), if you open the LSP logs, you should see a lot of panics probably. I want to hunt these down and write reproducible tests.

**Comment by tamasfe** [comment]
> BTW, are you on Discord? 

I don't normally use it, but sure, good idea, I'll join to make communication faster.

**Comment by schungx** [comment]
The Windows-specific issues are all resolved, and so I'll close this.
