### ISSUE TITLE
Process interpolated code in strings

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#46]
Currently all strings are processed as-is, and interpolations are ignored.

I don't know yet where to process these, as they will complicate the parse tree a whole lot.

**Comment by schungx** [comment]
> Currently all strings are processed as-is, and interpolations are ignored.

It would be dangerous, as there can be nested interpolations.  If you just count braces, you may end up going wrong.

```rust
`This is first level ${let s = `this is second level ${x}`; s` so there.`
```

> I don't know yet where to process these, as they will complicate the parse tree a whole lot.

What I do is, when I see a `` ` ``, I read a string until I get another `` ` `` (closing) or `${`.  If `${`, then I return the previous string as a partial segment, and start normal parsing again.  When I reach a statement that begins with `}`, then I start another partial string segment.  Repeat.

**Comment by schungx** [comment]
After thinking about this some more, I have an idea to fit the parsing of interpolated strings into the current LSP structure.  As I understand after Googling a bit, tokenizing an interpolated string is non-trivial.

The idea is to parse the interpolated string as a string of tokens, essentially like what is done with the current Rhai parser.

```js
`The answer is ${"!!!" + answer + "!!!"}.  QED.`
```

Upon seeing `` ` ``, the tokenizer should parse until it sees either:

* `` ` `` : for which it returns a `LIT_STR`
* `${` : for which it returns a `LIT_INTERP_STR` (new token type)

In your grammar, you need a special rule for interpolated strings:

```
Lit =
  'lit_int'
| 'lit_float'
| String
| 'lit_bool'
| 'lit_char'

String =
  'lit_str'
  'lit_interp_str' segments:('${' Expr '}'  'lit_str'?)+
```

**Comment by tamasfe** [comment]
I'll tag this as hard instead as it'll need special care in the HIR as well, will get back to this once everything else works.

**Comment by schungx** [comment]
That's correct.  The trick, it seems, is to convert the nested embedded expressions into structured syntax that can be parsed simply with a grammar.

So it seems like an interpolated string is nothing but a fancy function call, sort of.  You simply have literal strings instead of comma's separating expressions, and the first piece from `` ` `` till `${` as the function name.

**Comment by schungx** [comment]
So, just to think aloud along that idea...  take the following interpolated string:

```js
`The answer is ${`an ${if answer.is_even() { "even number" } else { "odd number" }}` + answer}.  QED.`
```

We parse it as if we have:

```rust
str_interp_the_answer_is(
    str_interp_an(  if answer.is_even() { "even number" } else { "odd number" } , "" ) + answer ,
    ". QED"
)
```
