### ISSUE TITLE
`in` as an operator

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#48]
We should parse `in` just as an operator for the sake of simplicity, then restrict its usability in the HIR where needed.

**Comment by schungx** [comment]
Well, it actually _is_ an operator.  It is parsed like a normal operator, except that internally it gets turned into a call to `contains` with the operands switched.  But syntax wise, it is an operator.

It does have a different precedence though.

**Comment by tamasfe** [comment]
I assigned the lowest binding power to it for now which is just above the default user-provided ones. (yeah it's now possible to provide custom operators that are valid identifiers).

**Comment by schungx** [comment]
> I assigned the lowest binding power to it for now

Precedence of the `in` operator is defined here: https://rhai.rs/book/engine/custom-op.html#operator-precedence
