### ISSUE TITLE
Handle windows file paths correctly

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#60]
We should normalize all file paths under windows including the ones in URLs before we work with them:

- account for percent encoding where needed
- either use `\` or `/` uniformly

**Comment by schungx** [comment]
Oops sorry, I believe canonical returns the UNC standard path format which is like \\?\c\Git\rhai

The file:///c:/Git/rhai format is the URI format, but I believe there are ways to translate between the two.

I'd suggest keeping to the URI format, which should work on both Windows and Unix.
