### ISSUE TITLE
Scope variables and custom operators not recognized.

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#68]
In the `definitions` example, when I click open `script.rhai`:

![image](https://user-images.githubusercontent.com/661318/181140340-243cceb2-3114-493c-aabb-5df6b525e2c9.png)

However, `hello_there` is already defined in `__scope__.d.rhai`:

```rust
module static;

let hello_there;
```

**Comment by schungx** [comment]
Also, if I change the script to:

![image](https://user-images.githubusercontent.com/661318/181140500-46ec9d5a-fda9-4c99-98f0-eb4df274c0c7.png)

Although `minus` is defined in `__static__.d.rhai`:

```rust
module static;

op minus(int, int) -> int;
```

**Comment by tamasfe** [comment]
Operators are ignored in the HIR right now (#66), the parser needs to know the allowed operator keywords so we need to process the definition files, and reparse the rest if the set of known custom keywords change.

The other issue is a bug, `let` definitions are ignored in definitions right now, if you change it to const, it will be recognized.

**Comment by tamasfe** [comment]
Huh, apparently `let`s were parsed but were missing from the AST definition.

**Comment by schungx** [comment]
> The other issue is a bug, `let` definitions are ignored in definitions right now, if you change it to const, it will be recognized.

Got it.  But if it is `const`, won't it be an error to assign to it?

**Comment by tamasfe** [comment]
> Got it. But if it is `const`, won't it be an error to assign to it?

Yes, renaming it to const is just a temporary fix, I'm working on the lsp to accept and not to ignore `let`-s in definitions.

**Comment by tamasfe** [comment]
The `let` issue has been fixed, and custom operators are tracked in the other issue.
