### ISSUE TITLE
Rhai Panel

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#7]
Show a dedicated VSCode activity panel for Rhai.

Things to display:
- [x] Syntax tree
- [ ] User integrations and context information (#3)

**Comment by tamasfe** [comment]
I cannot find a legitimate use-case right now, other than the syntax tree, which is useful only for development.

**Comment by schungx** [comment]
How do I install the lsp server to try this out?

**Comment by tamasfe** [comment]
https://github.com/rhaiscript/lsp#contributing These should be enough from the master branch, tell me if something doesn't work.

**Comment by schungx** [comment]
Unfortunately my primary machine is Windows...  do you  have a workflow for building it on Windows?

**Comment by tamasfe** [comment]
Unfortunately I don't have access to windows atm, the commands should be the same though.

You'll need to have nodejs installed.

From that step the setup is pretty much:

```
npm install --global yarn
npm install --global vsce
```

Then in the [`editors/vscode`](https://github.com/rhaiscript/lsp/tree/master/editors/vscode) directory:

```
yarn install
vsce package --no-yarn
code --install-extension --force rhai-0.0.0.vsix
```

The last command just installs the .vsix extension file in vscode, there are other methods to do that if that fails.

As for the language server, it's just a cargo binary `cargo install --path crates/lsp --debug`.

But yeah, I haven't tested any of this, I'll get a windows vm at some point in the next days.

**Comment by schungx** [comment]
Do I have to turn off the Rhai syntax highlighting extension first?

**Comment by tamasfe** [comment]
> Do I have to turn off the Rhai syntax highlighting extension first?

The syntax highlight will conflict but the rest should be fine.
