### ISSUE TITLE
Pretty-print HIR

### ISSUE THREAD

**Issue by tamasfe** [rhaiscript/lsp#72]
Right now debugging the HIR is somewhat painful, there is no way to easily print symbols in a scope, and even printing a single symbol can be a hassle due to all references being indexes.

**Comment by schungx** [comment]
The Rhai panel is a great help.  However, desperately need a popup menu item "Go to Panel" which just jumps to the relevant node in the syntax tree in the panel.

**Comment by tamasfe** [comment]
For reference, it is now also possible to dump the HIR via a vscode command.

I've already fixed a bug this way.
