### ISSUE TITLE
Probably parsing expression with unary operator.

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#76]
Parsing seems to be broken after a unary operator (such as `!`, `+` and `-`).

![image](https://user-images.githubusercontent.com/661318/181879410-8013aefc-da50-4ffb-a76d-c8396aa3f9ab.png)

It parses fine without any unary operator.

**Comment by tamasfe** [comment]
Hm, I either broke this very early on or has never worked. It's weird that none of the tests seem to cover this.
