### ISSUE TITLE
Scope variable in definition files problem with types

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#83]
Right now, `let variable;` in definition files have no type declaration.

When I add types to it:

```rust
let variable: String;
```

it screws up variable resolution in the LSP -- e.g. the goto-definition no longer works.

```rust
let variable: ?;
```

Marking the variable as `?` does continue to work.

**Comment by tamasfe** [comment]
I can't reproduce this, so I assume it was #84.

![image](https://user-images.githubusercontent.com/25967296/183409380-176c4077-d54b-4643-ac60-acb058a29b7c.png)
