### ISSUE TITLE
Range error with `rhai-scope`

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#85]
Failed to load.  Error log attached.

```text
panicked at 'Bad range: node range 0..487, range 505..524', C:\Users\Stephen\.cargo\registry\src\github.com-1ecc6299db9ec823\rowan-0.15.8\src\cursor.rs:786:13
```

[lsp_log.txt](https://github.com/rhaiscript/lsp/files/9285873/lsp_log.txt)

The error is raised in `collect_symbols` when collecting scope symbols.  `document_symbols.rs:79`

**Comment by schungx** [comment]
I wonder if this is yet another case of LF (Unix) vs CRLF (Windows)?  Because we're looking at improper range values here.

```rust
pub fn covering_element(&self, range: TextRange) -> SyntaxElement {
    let mut res: SyntaxElement = self.clone().into();
    loop {
        assert!(
            res.text_range().contains_range(range),
            "Bad range: node range {:?}, range {:?}",
            res.text_range(),
            range,
        );
        res = match &res {
            NodeOrToken::Token(_) => return res,
            NodeOrToken::Node(node) => match node.child_or_token_at_range(range) {
                Some(it) => it,
                None => return res,
            },
        };
    }
}
```

**Comment by schungx** [comment]
The range seems to be the exact variable definition statement inside a `rhai-scope` code block, so I believe some offsets are screwed up...

**Comment by schungx** [comment]
OK, I found a pattern.

Say, the beginning of a `rhai-scope` code block is at offset `n`.  It seems to be mistakenly added twice, so becomes `2 * n`.

**Comment by schungx** [comment]
Tried the latest version, but still getting range errors with `rhai-scope`.

**Comment by tamasfe** [comment]
Yeah I haven't touched on this yet.

**Comment by tamasfe** [comment]
Do you happen to have an MCVE for this?

**Comment by schungx** [comment]
Of course, it happens every single time when I open the `foo.rhai` file from `examples`.

Vscode will try 5 times, then fail the extension.

**Comment by tamasfe** [comment]
Seems to be a windows issue indeed, I do not account for CRLF somewhere, changing the file to LF makes the panics go away.

**Comment by schungx** [comment]
OK, changing that one file `foo.rhai` to LF makes _ALL_ the problems go away!  Everything Just Works(TM).

**Comment by schungx** [comment]
This seems to have fixed, even with CRLF.  Closing.
